Add SITL documentation
betaflight/betaflight.com pull request #156
Opened 2023-02-20 02:40 UTC by haslinghuis

2023-02-20 03:41 UTC, haslinghuis commented
@freasy 

did not remove Building in Windows document
added a SITL document with /img and /resource items

Somehow automation is making it hard to contribute as it did work locally in test browser

2023-02-20 06:53 UTC, freasy commented
> @freasy
> 
> did not remove Building in Windows document added a SITL document with /img and /resource items
> 
> Somehow automation is making it hard to contribute as it did work locally in test browser

The build is fine, only name and title checks fail, which are not that important. Where should I look at?

2023-02-20 13:51 UTC, KarateBrot requested changes

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +SITL (software in the loop) simulator allows you to run betaflight without any hardware.
```suggestion
SITL (software in the loop) simulator allows you to run Betaflight without any hardware.
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +On WSL2, you need to configure the BetaFlight following [document here](/docs/development/Building-in-Windows).
```suggestion
On WSL2, you need to configure the Betaflight following [document here](/docs/development/Building-in-Windows).
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +Build BetaFlight with
```suggestion
Build Betaflight with
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +Import the quadcopter for RealFlight and BetaFlight at **models/Quadcopter X Betaflight - flightaxis_AV.RFX** in RealFlightBridge. A detailed guide for improtanting can be found [here](https://ardupi
```suggestion
Import the quadcopter for RealFlight and Betaflight at **models/Quadcopter X Betaflight - flightaxis_AV.RFX** in RealFlightBridge. A detailed guide for improtanting can be found [here](https://ardupilot.org/dev/docs/sitl-with-realflight.html).
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +3. Start BetaFlight SITL.
```suggestion
3. Start the Betaflight SITL.
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +   Then go to the BetaFlight root and start SITL with this IP.
```suggestion
   Then go to the Betaflight root and start the SITL with this IP.
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +   Then you can open BetaFlight configurator on **Windows** to connect to RealFlight via **WSL IP**.
```suggestion
   Then you can open the Betaflight Configurator on **Windows** to connect to RealFlight via **WSL IP**.
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +   After connect to BetaFlight you need to apply this [DIFF file](/sitl/BTFL_quadcopter_rf9.txt) and set the arming switch with your controller.
```suggestion
   After connect to Betaflight you need to apply this [DIFF file](/sitl/BTFL_quadcopter_rf9.txt) and set the arming switch with your controller.
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +4. Finally, you can arm and take-off the Quadcopter with BetaFlight SITL in RealFlight with your controller.
```suggestion
4. Finally, you can arm and take-off the Quadcopter with Betaflight SITL in RealFlight with your controller.
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +3. connect your transmitter and fly/test, used app to send `MSP_SET_RAW_RC`, see [code](https://github.com/cs8425/msp-controller).
```suggestion
1. Start Betaflight: `./obj/main/betaflight_SITL.elf`
2. Start Gazebo: `gazebo --verbose ./iris_arducopter_demo.world`
3. Connect your transmitter and fly/test, used app to send `MSP_SET_RAW_RC`, see [code](https://github.com/cs8425/msp-controller).
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +size can be changed in `src/main/target/SITL/pg.ld` >> `__FLASH_CONFIG_Size`
```suggestion
Size can be changed in `src/main/target/SITL/pg.ld` >> `__FLASH_CONFIG_Size`
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +gazebo -> betaflight `udp://127.0.0.1:9003`
```suggestion
Betaflight -> Gazebo `udp://127.0.0.1:9002`
Gazebo -> Betaflight `udp://127.0.0.1:9003`
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +I recommend to use transmitter with OpenTX/EdgeTX as a game controller. In addition, mixers of channel 5 and 6 should be mapped to two switches for arming and changing mode.
```suggestion
We recommend to use transmitter with OpenTX/EdgeTX as a game controller. In addition, mixers of channel 5 and 6 should be mapped to two switches for arming and changing mode.
```

2023-02-20 13:51 UTC, KarateBrot commented on docs/development/SITL.mdx
> +   In WSL entering
```suggestion
   In WSL enter
```

2023-02-20 14:14 UTC, haslinghuis commented
Done. Thanks @KarateBrot.

2023-02-20 14:58 UTC, KarateBrot requested changes
Found some more 😀

Btw. do we need to worry about the failing github checks?

2023-02-20 14:58 UTC, KarateBrot commented on docs/development/Building-in-Windows.md
> +For various reasons, a custom build of Betaflight might be needed. A user might want to enable certain features that are disabled on his / her target, for example. This guide provides the basic instr
```suggestion
For various reasons, a custom build of Betaflight might be needed. A user might want to enable certain features that are disabled on his / her target, for example. This guide provides the basic instructions needed to build Betaflight on a Windows system. One option is given:
```

2023-02-20 14:58 UTC, KarateBrot commented on docs/development/SITL.mdx
> +run `make TARGET=SITL`
```suggestion
Run `make TARGET=SITL`
```

2023-02-20 14:58 UTC, KarateBrot commented on docs/development/SITL.mdx
> +to avoid simulation speed slow down, suggest to set some settings belows:
```suggestion
To avoid the simulation speed slowing down, it is suggested to set some settings shown below:
```

2023-02-21 09:11 UTC, freasy approved these changes

2023-02-21 11:58 UTC, KarateBrot approved these changes

2023-02-21 12:18 UTC, merged