Update connector standard
betaflight/betaflight.com pull request #182
Opened 2023-05-05 13:46 UTC by haslinghuis

Reverts ESC Ground Voltage to Voltage Ground

2023-05-05 14:26 UTC, SupaflyFPV submitted a review, later dismissed

2023-05-08 05:31 UTC, KarateBrot requested changes
What about all the other pin definitions? It seems like besides the ESC connector, all other ones also break our own defined rule laid out in the manufacturer design guidelines, which is
```
V+ / GND / Signal
```
so that high voltage V+ cannot interfere as much with signal lines

2023-05-08 13:30 UTC, McGiverGim submitted a review, later dismissed

2023-05-08 13:55 UTC, KarateBrot requested changes

2023-05-08 15:45 UTC, haslinghuis commented on docs/manufacturer/connector-standard.mdx
> +This connector type is optional for drone manufacturers, allowing them to choose the connector that best suits their needs as long they provide a harness for both platforms.
Done :+1:

2023-05-08 16:43 UTC, KarateBrot approved these changes

2023-05-08 17:16 UTC, merged