Add Missing board file
betaflight/betaflight.com pull request #207
Opened 2023-07-20 15:48 UTC by HThuren

This file as a WIKI reference in unified configuation files.
Use in configuration fiele are: #wiki https://betaflight.com/docs/wiki/boards/missing

Will differ from the action when no #wiki reference are found in the unified configuration file

2023-07-20 16:30 UTC, haslinghuis requested changes

2023-08-03 18:24 UTC, HThuren commented on docs/wiki/boards/Missing.md
> +You can try to find a previous board / board version from same Manufacturer at https://betaflight.com/docs/wiki/boards
the bord.md files are found at https://betaflight.com/docs/wiki/boards/
the index to all board files are https://betaflight.com/docs/category/boards
not sure I understand, but seems to work

2023-08-03 18:45 UTC, haslinghuis commented on docs/wiki/boards/Missing.md
> +# Missing Board decription
```suggestion
# Missing Board Description
```

2023-08-03 18:46 UTC, haslinghuis commented on docs/wiki/boards/Missing.md
> +The Betaflight WIKI still haven't got a description for this board or version of board.
```suggestion
The Betaflight WiKi does not have a description for this board.
```

2023-08-03 18:52 UTC, haslinghuis commented on docs/wiki/boards/Missing.md
> +Also you can request the Manufacturer to create this description as described at [https://betaflight.com/docs/manufacturer/manufacturer-design-guidelines](https://betaflight.com/docs/manufacturer/man
```suggestion
You can ask the Manufacturer to add this description as described in [https://betaflight.com/docs/manufacturer/manufacturer-design-guidelines](https://betaflight.com/docs/manufacturer/manufacturer-design-guidelines)
```

2023-08-03 19:46 UTC, HThuren commented on docs/wiki/boards/Missing.md
> +The Betaflight WIKI still haven't got a description for this board or version of board.
You have better English :-)

2023-08-03 20:25 UTC, haslinghuis approved these changes

2023-08-06 14:22 UTC, nerdCopter approved these changes

2023-08-06 14:46 UTC, SupaflyFPV approved these changes

2023-08-06 14:54 UTC, merged