note about colour formats
betaflight/betaflight.com pull request #291
Opened 2023-12-20 20:58 UTC by ctzsnooze

Added notes about an HSL colour viewer, colour formats, and tidied up.
No code changes, just comments.

2023-12-20 21:05 UTC, nerdCopter commented
![image](https://github.com/betaflight/betaflight.com/assets/56646290/6612f8c8-489b-4c8d-ab3b-8cfc570defbe)

2023-12-22 20:44 UTC, haslinghuis requested changes

2023-12-22 20:44 UTC, haslinghuis commented on tailwind.config.js
> +          800: '#CC7E00', // browm,         Hue 37, Luminance 40
```suggestion
          800: '#CC7E00', // brown,         Hue 37, Luminance 40
```

2023-12-22 20:45 UTC, haslinghuis approved these changes

2023-12-24 00:03 UTC, blckmn approved these changes

2023-12-24 00:03 UTC, merged