Make Logos Adapt to Color Theme
betaflight/betaflight.com pull request #315
Opened 2024-01-01 14:21 UTC by KarateBrot

- Make logos adapt to color theme
- Fix sponsor logos
- Small layout changes to the BF logo on the landing page

# Before
![grafik](https://github.com/betaflight/betaflight.com/assets/19867640/a6802331-3efa-4d6e-83f3-fe763649fa27)
![grafik](https://github.com/betaflight/betaflight.com/assets/19867640/4083d892-a5a4-4164-9a31-5fe4708f2ceb)

# After
![grafik](https://github.com/betaflight/betaflight.com/assets/19867640/e5ffed03-6a97-44e2-9f30-6d585b954724)
![grafik](https://github.com/betaflight/betaflight.com/assets/19867640/1db6a6f6-4338-46a8-96df-13c1ee4fe9fe)

2024-01-01 17:02 UTC, SupaflyFPV commented
looks great, only thing is the Axis logo rather dominates if it resizes according to height?

2024-01-02 04:43 UTC, KarateBrot commented
> looks great, only thing is the Axis logo rather dominates if it resizes according to height?

I was not able to fix this. Something seems to overwrite the appearance. Maybe I can figure it out later if no one beats me to it

2024-01-02 18:06 UTC, haslinghuis reviewed
As configurator gets the content from cloud API does this solve the inverted image for Axis too?

For dark mode the Axis logo does not work with `#315` checked out?

![image](https://github.com/betaflight/betaflight.com/assets/8344830/32ae923b-7b2f-4fca-8fed-b3c2a815a52e)

![image](https://github.com/betaflight/betaflight.com/assets/8344830/4a91eb5c-47a7-4328-baae-9bc3bcc96e89)

2024-01-02 18:11 UTC, haslinghuis requested changes
Axis logo does not work because it is capitalized.

![image](https://github.com/betaflight/betaflight.com/assets/8344830/ab40edb9-b306-4881-a2af-bcdf269e764f)

2024-01-03 02:40 UTC, KarateBrot commented
> @haslinghuis:
> Axis logo does not work because it is capitalized.

While working on the PR I renamed it TWICE but it still didn't register. And while trying to fix it, it still didn't want to register the change. Probably a git bug. I now got it working by first pushing a commit with the deleted file and then re-added the file 🙄
Interestingly enough, my browser displayed the logo correctly even though the file name was capitalized.

> @haslinghuis:
> As configurator gets the content from cloud API does this solve the inverted image for Axis too?

No, this is completely independent from the configurator source files. At least it should be.

2024-01-03 04:10 UTC, ctzsnooze commented
Looks really good, except that the logos suddenly get huge when the screen is narrow enough in the Relations:Sponsors page.  It looks like this:

![Screen Shot 2024-01-02 at 20 39 49](https://github.com/betaflight/betaflight.com/assets/11737748/842bfd5e-2c68-4dc1-abc6-46147c8eae6e)

In contrast, the logos on the main landing page don't have that problem.

Also the row of three images further down the page does not scale smaller very well, getting too big for small screens..

Please don't remove the duplicate copy of `sponsors.md` at src/Pages/.  This is needed since it will get displayed by the outgoing link from Configurator.  If you remove it, people clicking on the sponsor icon in Configurator will go to betaflight.com/sponsors and be returned `Page not found`.  PR #310 solves this problem in a different way, but has not yet been merged.  There is another way using a plugin.  Until one of these are merged, we need to keep a copy of sponsors.md in the  src/Pages/ directory.

2024-01-03 04:11 UTC, ctzsnooze commented on docs/relations/sponsors.mdx
> +<div className="flex flex-col items-center backdrop-blur-md shadow-xl p-4 rounded-2xl bg-neutral-500/10 grid md:grid-cols-4 gap-4 mb-4">
changing `flex-col` to `flex-cols-4` and removing `grid md:grid-cols-4` fixes the behaviour with very small screen widths.

2024-01-03 04:15 UTC, ctzsnooze commented on docs/relations/sponsors.mdx
> +      className="no-effect w-4/5 themeInvert"
HQprop now seems too small; changing `w-⅘` to `w-full`, balances it better with the others.

2024-01-03 04:16 UTC, ctzsnooze commented on docs/relations/sponsors.mdx
> +      className="no-effect w-full themeInvert"
radiomaster image now seems larger than before; `w-4/5` seems to work better than `w-full`.

2024-01-03 04:17 UTC, ctzsnooze commented on docs/relations/sponsors.mdx
> +      className="no-effect w-full"
Dogcom might be better at 4/5ths size than `w-full`

2024-01-03 04:22 UTC, ctzsnooze commented
Also we can perhaps better balance the sizes of the images... with the changes to the images, HQ seems smaller than before, and radiomaster is more dominant than before.

Current appearance
![Screen Shot 2024-01-02 at 21 21 11](https://github.com/betaflight/betaflight.com/assets/11737748/f7fea749-94af-4fae-90f8-66566fc7eabe)

With the following suggested changes:
- HQ to ⅘ from full
- radiomaster from full to ⅘
- dogcom from full to ⅘
it looks like th
![Screen Shot 2024-01-02 at 21 18 11](https://github.com/betaflight/betaflight.com/assets/11737748/edfc8a5b-43b0-4a40-bbd8-8e3a8fd01616)
is:

2024-01-03 17:29 UTC, haslinghuis approved these changes
Let's merge the fix - we need our focus on firmware and client software as we can always improve documentation after release.

2024-01-04 02:25 UTC, ctzsnooze commented
It is trivial for @KarateBrot to fix this PR so that it works nicely at small screen sizes.

It is unfair on HQProp to make their logo significantly smaller in visual impact than the others.
It is not OK that at small screen sizes the 'fix' fails to look good.  That could affect all phone users.
These two things need to be fixed.

It is trivial for @KarateBrot to fix those issues in this PR, and I already explained how to do it.  

However if he is short of time, we can merge and I'll make a followup PR to implement those fixes.  Hence I will approve on that basis.

2024-01-04 02:26 UTC, ctzsnooze submitted a review, later dismissed

2024-01-04 02:48 UTC, ctzsnooze commented on docs/relations/sponsors.mdx
> +<div className="flex flex-col items-center backdrop-blur-md shadow-xl p-4 rounded-2xl bg-neutral-500/10 grid md:grid-cols-4 gap-4 mb-4">
Please ignore the previous comment, must have been an image caching problem; sizing of this image now seems OK with code in the PR.

2024-01-04 02:49 UTC, ctzsnooze commented on docs/relations/sponsors.mdx
> +      className="no-effect w-4/5 themeInvert"
Perhaps it was a caching error, but the image sizes now appear OK after rebooting and force-refreshing.
Please ignore the previous suggestion.

2024-01-04 02:49 UTC, ctzsnooze commented on docs/relations/sponsors.mdx
> +      className="no-effect w-full themeInvert"
Perhaps it was a caching error, but the image sizes now appear OK after rebooting and force-refreshing.
Please ignore the previous suggestion.

2024-01-04 02:53 UTC, ctzsnooze commented
Sorry PLEASE DO NOT MERGE unless this PR restores a duplicate of `docs/relations/sponsors.mdx` in `pages/` so that we do not break the click on the link in configurator.
Or else merge PR #310 which means you won't have to do that.

2024-01-04 09:44 UTC, KarateBrot commented
@ctzsnooze I added the sponsors page again and let it fetch the content to prevent the need to maintain duplicates. Feel free to change the styling of whatever you don't like in this PR. This PR is more about making the logos adapt to the color theme.

2024-01-04 13:54 UTC, ctzsnooze approved these changes

2024-01-04 13:57 UTC, ctzsnooze commented
PR tests out 100% perfectly now.   The bug on squashing to very narrow screen sizes has been fixed.  Looks great in both night and day modes.
Approved, and ready to merge, I think.

2024-01-04 13:57 UTC, ctzsnooze approved these changes

2024-01-04 15:04 UTC, nerdCopter commented
@KarateBrot  `git mv -f OldFileNameCase newfilenamecase` might have worked as well.

unsure what operating system you run. Windows is case-insensitive mostly.  there is also the git variable : `git config [--global] core.ignorecase [true|false]`

2024-01-04 15:06 UTC, nerdCopter approved these changes

2024-01-04 15:18 UTC, haslinghuis approved these changes

2024-01-04 15:18 UTC, merged