Partner Program Page Updates
betaflight/betaflight.com pull request #423
Opened 2024-05-16 22:48 UTC by SupaflyFPV

We've modified the partner program page with @KarateBrot logos and further text

2024-05-17 12:55 UTC, nerdCopter commented
a cursor is being shown here
![image](https://github.com/betaflight/betaflight.com/assets/56646290/4c546116-d76a-4537-8708-165fcc3990bb)

maybe the dots can can be removed or replaced by something that looks like a timer.
as @chmelevskij reported as well, dots typically represent different panes/views.
another option, maybe the dots should increment only when the logos change. but meh.

2024-05-23 12:03 UTC, KarateBrot requested changes

2024-05-23 12:03 UTC, KarateBrot commented on docs/development/manufacturer/partner-program.mdx
> +    className="no-effect md:w-1/4 mt-6 mb-2"
```suggestion
    className="no-effect md:w-1/4 mt-6 mb-2"
    style={{width: 200}}
```

2024-05-23 20:04 UTC, haslinghuis approved these changes

2024-05-23 20:29 UTC, nerdCopter approved these changes

2024-05-24 06:41 UTC, blckmn approved these changes

2024-05-24 10:30 UTC, KarateBrot approved these changes

2024-05-24 11:31 UTC, merged